version: "2"

linters:
  default: all
  disable:
    - exhaustruct
    - depguard
    - staticcheck
    - nilerr
    - nlreturn
    - noinlineerr
    - paralleltest
    - revive
    - testpackage
    - unparam
    - varnamelen
    - whitespace
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - path: "(above_|below_)"
        linters:
          - exhaustruct
          - forbidigo
          - goconst
          - gocritic
          - lll
          - usestdlibvars
          - mnd
          - nestif
          - unused

