run:
  skip-dirs:
    - examples

linters:
  enable-all: true
  disable:
    - interfacer
    - structcheck
    - deadcode
    - nosnakecase
    - ifshort
    - golint
    - scopelint
    - exhaustivestruct
    - maligned
    - varcheck
    - rowserrcheck
    - wastedassign
    - gci
    - wsl
    - exhaustruct
    - paralleltest
    - testpackage
    - varnamelen