version: 2

linters:
  enable-all: true
  disable:
    - staticcheck
  exclusions:
    rules:
      - path: above_*
        linters:
          - unused
      - path: below_*
        linters:
          - unused

